(()=>{'use strict';
const low=v=>String(v||'').trim().toLowerCase();
const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
function currentWallets(){const rows=Array.isArray(window.__YUAN_CURRENT_ROWS__)?window.__YUAN_CURRENT_ROWS__:[];return new Set(rows.map(r=>low(r['Proxy Wallet'])).filter(w=>/^0x[a-f0-9]{40}$/.test(w)))}
function walletOf(tr){const td=tr.querySelectorAll('td')[1];if(!td)return'';const href=td.querySelector('a')?.getAttribute('href')||'';let m=href.match(/profile\/(0x[a-fA-F0-9]{40})/);if(m)return low(m[1]);m=(td.getAttribute('title')||td.textContent||'').match(/0x[a-fA-F0-9]{40}/);return m?low(m[0]):''}
function detailRows(){const tb=document.getElementById('yeTable');if(!tb)return[];const set=currentWallets();const out=[];for(const tr of tb.querySelectorAll('tr')){const td=tr.querySelectorAll('td');if(td.length<10)continue;const wallet=walletOf(tr);if(set.size&&!set.has(wallet))continue;out.push({account:td[0].textContent.trim(),wallet,relay:td[2].textContent.trim(),exchange:td[3].textContent.trim(),exchangeAddress:td[4].getAttribute('title')||td[4].textContent.trim(),direction:td[5].textContent.trim(),amount:td[6].textContent.trim(),time:td[7].textContent.trim(),status:td[8].textContent.trim()})}return out}
function resolvedRows(){const box=document.getElementById('yeResolvedTxBox');if(!box)return[];const out=[];for(const tr of box.querySelectorAll('tbody tr')){const td=tr.querySelectorAll('td');if(td.length<9)continue;const cp=(td[7].querySelector('[data-copy]')?.dataset.copy||td[7].getAttribute('title')||td[7].textContent||'').trim();const ex=td[8].textContent.trim();out.push({relay:td[0].textContent.trim(),chain:td[1].textContent.trim(),tx:td[2].getAttribute('title')||td[2].textContent.trim(),direction:td[3].textContent.trim(),token:td[4].textContent.trim(),amount:td[5].textContent.trim(),time:td[6].textContent.trim(),counterparty:cp,exchange:ex})}return out}
function cleanExchange(s){s=String(s||'').trim();if(!s||/待標記|未發現|查詢|失敗|未知|—/.test(s))return'';return s.replace(/\s*\/\s*(台灣|海外)\s*$/,'').trim()}
function render(){let card=document.getElementById('yuanExchangeSummary');const engine=document.getElementById('yuanExchangeEngine');if(!engine)return;if(!card){card=document.createElement('div');card.className='card';card.id='yuanExchangeSummary';card.innerHTML='<h2>📋 本次交易所彙總</h2><p class="sub">每個 Polymarket Wallet 一列；同時命中多家交易所會全部列出且不重複。</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin:10px 0"><button id="yesRefresh">重新整理彙總</button><button id="yesCsv" class="secondary">下載本次完整 CSV</button></div><div id="yesState" class="progress">等待資料…</div><div style="overflow:auto;max-height:480px;border:1px solid #d8e0e8;border-radius:9px;margin-top:10px"><table class="mini" style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th>Polymarket 帳號</th><th>Wallet</th><th>交易所往來</th><th>命中筆數</th></tr></thead><tbody id="yesBody"></tbody></table></div>';engine.parentNode.insertBefore(card,engine);document.getElementById('yesRefresh').onclick=render;document.getElementById('yesCsv').onclick=downloadCsv}
const details=detailRows(), resolved=resolvedRows(), map=new Map();for(const r of details){if(!map.has(r.wallet))map.set(r.wallet,{account:r.account,wallet:r.wallet,ex:new Set(),count:0});const e=cleanExchange(r.exchange);if(e){map.get(r.wallet).ex.add(e);map.get(r.wallet).count++}}
/* supplement exchange names visible in resolved counterparty table when the wallet-level row has not yet copied them */
const visibleEx=[...new Set(resolved.map(r=>cleanExchange(r.exchange)).filter(Boolean))];if(map.size===1&&visibleEx.length){const x=[...map.values()][0];visibleEx.forEach(e=>x.ex.add(e));x.count=Math.max(x.count,visibleEx.length)}
const body=document.getElementById('yesBody');body.innerHTML='';for(const x of map.values()){const tr=document.createElement('tr');tr.innerHTML=`<td>${x.account||'—'}</td><td class="wallet" title="${x.wallet}">${x.wallet?x.wallet.slice(0,8)+'…'+x.wallet.slice(-6):'—'}</td><td class="ok">${x.ex.size?[...x.ex].join('、'):'尚未命中交易所'}</td><td>${x.count}</td>`;body.appendChild(tr)}if(!map.size)body.innerHTML='<tr><td colspan="4">本次尚無可彙總資料</td></tr>';const hit=[...map.values()].filter(x=>x.ex.size).length;document.getElementById('yesState').textContent=`本次 Wallet ${map.size} 個｜有交易所往來 ${hit} 個｜完整明細 ${details.length} 筆`}
function downloadCsv(){const a=detailRows(),b=resolvedRows();const lines=['Polymarket帳號,Polymarket Wallet,Relay,交易所,交易所地址,方向,金額,時間,狀態,鏈,TxHash,Token,實際對手地址'];for(const r of a)lines.push([r.account,r.wallet,r.relay,r.exchange,r.exchangeAddress,r.direction,r.amount,r.time,r.status,'','','',''].map(esc).join(','));for(const r of b)lines.push(['','','',r.exchange,'',r.direction,r.amount,r.time,'OKLink/對手地址明細',r.chain,r.tx,r.token,r.counterparty].map(esc).join(','));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const u=URL.createObjectURL(blob),aEl=document.createElement('a');aEl.href=u;aEl.download='YUAN_本次交易所完整資料_'+new Date().toISOString().slice(0,10)+'.csv';aEl.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function boot(){render();const obs=new MutationObserver(()=>setTimeout(render,250));obs.observe(document.body,{childList:true,subtree:true});setInterval(render,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();