(()=>{'use strict';
const low=v=>String(v||'').trim().toLowerCase();
const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
function rows(){return Array.isArray(window.__YUAN_CURRENT_ROWS__)?window.__YUAN_CURRENT_ROWS__:[]}
function wallets(){const m=new Map();for(const r of rows()){const w=low(r['Proxy Wallet']);if(/^0x[a-f0-9]{40}$/.test(w)&&!m.has(w))m.set(w,{wallet:w,account:r['帳號名稱']||r['暱稱']||''})}return m}
function activeWallet(){const texts=[document.getElementById('yeProgress')?.textContent||'',document.getElementById('globalProgress')?.textContent||''].join(' ');const m=texts.match(/0x[a-fA-F0-9]{40}/);return m?low(m[0]):''}
function cleanExchange(s){s=String(s||'').trim();if(!s||/待標記|未發現|查詢|失敗|未知|非交易所|Uniswap|Relay|1inch|PancakeSwap|SushiSwap|Curve|Aave|—/.test(s))return'';return s.replace(/\s*\/\s*(台灣|海外)\s*$/,'').trim()}
function resolvedForActive(){const box=document.getElementById('yeResolvedTxBox'),out=[];if(!box)return out;for(const tr of box.querySelectorAll('tbody tr')){const td=tr.querySelectorAll('td');if(td.length<9)continue;const cp=(td[7].querySelector('[data-copy]')?.dataset.copy||td[7].getAttribute('title')||td[7].textContent||'').trim();const ex=cleanExchange(td[8].textContent);out.push({relay:td[0].textContent.trim(),chain:td[1].textContent.trim(),tx:td[3]?.textContent.trim()||'',direction:td[6]?.textContent.trim()||'',counterparty:cp,exchange:ex,rawLabel:td[8].textContent.trim()})}return out}
function ensure(){let card=document.getElementById('yuanExchangeSummary'),engine=document.getElementById('yuanExchangeEngine');if(!engine)return null;if(!card){card=document.createElement('div');card.className='card';card.id='yuanExchangeSummary';card.innerHTML='<h2>📋 本次交易所彙總</h2><p class="sub">只顯示已完成 OKLink 驗證的結果；未驗證 Wallet 不再沿用舊快取判定。</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin:10px 0"><button id="yesRefresh">重新整理彙總</button><button id="yesCsv" class="secondary">下載本次完整 CSV</button></div><div id="yesState" class="progress">等待資料…</div><div style="overflow:auto;max-height:480px;border:1px solid #d8e0e8;border-radius:9px;margin-top:10px"><table class="mini" style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr><th>Polymarket 帳號</th><th>Wallet</th><th>交易所往來</th><th>狀態</th></tr></thead><tbody id="yesBody"></tbody></table></div>';engine.parentNode.insertBefore(card,engine);document.getElementById('yesRefresh').onclick=render;document.getElementById('yesCsv').onclick=downloadCsv}return card}
function render(){if(!ensure())return;const map=wallets(),aw=activeWallet(),rr=resolvedForActive(),ex=[...new Set(rr.map(x=>x.exchange).filter(Boolean))];const body=document.getElementById('yesBody');body.innerHTML='';let verified=0,hits=0;for(const x of map.values()){let txt='尚未完成 OKLink 驗證',status='未驗證';if(x.wallet===aw&&rr.length){verified++;if(ex.length){txt=ex.join('、');status='已驗證';hits++}else{txt='未發現明確交易所';status='已驗證'}}const tr=document.createElement('tr');tr.innerHTML=`<td>${x.account||'—'}</td><td class="wallet" title="${x.wallet}">${x.wallet.slice(0,8)}…${x.wallet.slice(-6)}</td><td class="${ex.length&&x.wallet===aw?'ok':''}">${txt}</td><td>${status}</td>`;body.appendChild(tr)}if(!map.size)body.innerHTML='<tr><td colspan="4">本次尚無 Wallet 資料</td></tr>';document.getElementById('yesState').textContent=`本次 Wallet ${map.size} 個｜已完成 OKLink 驗證 ${verified} 個｜命中交易所 ${hits} 個`}
function downloadCsv(){const map=wallets(),aw=activeWallet(),rr=resolvedForActive(),ex=[...new Set(rr.map(x=>x.exchange).filter(Boolean))];const lines=['Polymarket帳號,Polymarket Wallet,交易所往來,驗證狀態,Relay,Chain,TxHash,方向,實際對手地址,原始標籤'];for(const x of map.values()){const active=x.wallet===aw&&rr.length;if(!active)lines.push([x.account,x.wallet,'','未驗證','','','','','',''].map(esc).join(','));else if(!rr.length)lines.push([x.account,x.wallet,'未發現明確交易所','已驗證','','','','','',''].map(esc).join(','));else for(const r of rr)lines.push([x.account,x.wallet,r.exchange||'', '已驗證',r.relay,r.chain,r.tx,r.direction,r.counterparty,r.rawLabel].map(esc).join(','))}const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='YUAN_本次交易所驗證資料_'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function boot(){render();const o=new MutationObserver(()=>setTimeout(render,300));o.observe(document.body,{childList:true,subtree:true});setInterval(render,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();