const $=id=>document.getElementById(id);
function addr(v){const m=String(v||'').match(/0x[a-fA-F0-9]{40}/);return m?m[0].toLowerCase():''}
function parseCSV(t){t=t.replace(/^\uFEFF/,'');let a=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){const x=t[i],n=t[i+1];if(x==='"'){if(q&&n==='"'){c+='"';i++}else q=!q}else if(x===','&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;r.push(c);c='';if(r.some(v=>v!==''))a.push(r);r=[]}else c+=x}if(c!==''||r.length){r.push(c);a.push(r)}if(!a.length)return[];const h=a[0].map(x=>x.trim());return a.slice(1).map(v=>Object.fromEntries(h.map((k,i)=>[k,v[i]??''])))}
async function get(){return await chrome.storage.local.get({rows:[],addresses:[],results:[],running:false,index:0})}
async function put(x){await chrome.storage.local.set(x)}
function render(s){$('status').textContent=`CSV ${s.rows.length} 筆｜Counterparty ${s.addresses.length} 個｜結果 ${s.results.length} 筆｜目前 ${Math.min(s.index,s.addresses.length)}/${s.addresses.length}${s.running?'｜執行中':''}`;$('results').innerHTML=s.results.slice().reverse().map(r=>`<div class="r"><b>${r.Exchange||'NO_TAG'}</b>｜${r.OKLinkTag||''}<br>${r.OriginalAddress}<br>${r.Evidence||''}</div>`).join('')}
$('import').onclick=async()=>{const f=$('file').files[0];if(!f)return alert('請先選 CSV');const rows=parseCSV(await f.text());const addresses=[...new Set(rows.map(r=>addr(r.Counterparty||r.CounterpartyAddress||r.Recipient||r.To)).filter(Boolean))];const s={rows,addresses,results:[],running:false,index:0};await put(s);render(s)};
$('start').onclick=async()=>{const s=await get();if(!s.addresses.length)return alert('請先匯入 CSV');await put({running:true});chrome.runtime.sendMessage({type:'START'});render(await get())};
$('stop').onclick=async()=>{await put({running:false});render(await get())};
$('export').onclick=async()=>{const s=await get();if(!s.results.length)return alert('目前沒有結果');const h=['OriginalAddress','MatchedAddress','MatchLevel','Status','Exchange','OKLinkTag','TxId','Evidence','CheckedAt'];const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const t=['\ufeff'+h.join(','),...s.results.map(r=>h.map(k=>q(r[k])).join(','))].join('\r\n');const u=URL.createObjectURL(new Blob([t],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`YUAN_OKLink_Batch_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
chrome.storage.onChanged.addListener(()=>get().then(render));get().then(render);