const KNOWN={
'0x477b8d5ef7c2c42db84deb555419cd817c336b6f':{exchange:'MaiCoin',region:'台灣',tag:'MaiCoin'},
'0x7a83f06d30c8fc063dcb632b2540a9cc4835709a':{exchange:'BitoPro',region:'台灣',tag:'BitoPro'},
'0xb1ecc5c8bbb3f977d2be80491373fbea9ad62d5b':{exchange:'BitoPro',region:'台灣',tag:'BitoPro User'},
'0x0853ea40b121f9135d7e0c07fae35d59aedb4d0b':{exchange:'Kraken',region:'海外',tag:'Kraken'},
'0xba2987a1a6b8662b8fa04c8512f7fbec346af336':{exchange:'OKX',region:'海外',tag:'OKX Hot Wallet'},
'0x343d752bb710c5575e417edb3f9fa06241a4749a':{exchange:'OKX',region:'海外',tag:'OKX Hot Wallet'},
'0xe7804c37c13166ff0b37f5ae0bb07a3aebb6e245':{exchange:'Binance',region:'海外',tag:'Binance'},
'0xdfd5293d8e347dfe59e90efd55b2956a1343963d':{exchange:'Binance',region:'海外',tag:'Binance'},
'0xee7ae85f2fe2239e27d9c1e23fffe168d63b4055':{exchange:'Binance',region:'海外',tag:'Binance Hot Wallet_1'},
'0x505e71695e9bc45943c58adec1650577bca68fd9':{exchange:'Binance',region:'海外',tag:'Binance Withdraw_3'},
'0x290275e3db66394c52272398959845170e4dcb88':{exchange:'Binance',region:'海外',tag:'Binance Withdraw_2'},
'0xcb39c5b0db9c5b6bd1d9273dccc2f98f532a8bc6':{exchange:'Coinbase',region:'海外',tag:'Coinbase'},
'0x4d8336bda6c11bd2a805c291ec719baedd10acb9':{exchange:'Coinbase',region:'海外',tag:'Coinbase Deposit'},
'0x0d0707963952f2fba59dd06f2b425ace40b492fe':{exchange:'Gate',region:'海外',tag:'Gate.io'},
'0x51e3d44172868acc60d68ca99591ce4230bc75e0':{exchange:'MEXC',region:'海外',tag:'MEXC'},
'0xf89d7b9c864f589bbf53a82105107622b35eaa40':{exchange:'Bybit',region:'海外',tag:'Bybit'}
};
const CHAINS=[1,10,56,137,8453,42161,43114];
const OKSHORT={1:'ETH',10:'OP',56:'BSC',137:'POLYGON',8453:'BASE',42161:'ARBITRUM',43114:'AVAXC'};
function normName(s=''){s=String(s).toLowerCase();if(s.includes('maicoin')||s.includes('max exchange'))return['MaiCoin','台灣'];if(s.includes('bitopro'))return['BitoPro','台灣'];for(const [needle,name] of [['binance','Binance'],['okx','OKX'],['coinbase','Coinbase'],['bybit','Bybit'],['kraken','Kraken'],['gate.io','Gate'],['gate','Gate'],['mexc','MEXC'],['kucoin','KuCoin'],['bitget','Bitget'],['crypto.com','Crypto.com'],['huobi','HTX'],['htx','HTX'],['bitfinex','Bitfinex'],['upbit','Upbit']])if(s.includes(needle))return[name,'海外'];return null;}
function headers(){const h={accept:'application/json'};if(process.env.ROUTESCAN_API_KEY)h.apikey=process.env.ROUTESCAN_API_KEY;return h;}
async function accountRows(address,chainId,action){const u=new URL(`https://api.routescan.io/v2/network/mainnet/evm/${chainId}/etherscan/api`);for(const [k,v] of Object.entries({module:'account',action,address,page:'1',offset:'1000',sort:'desc'}))u.searchParams.set(k,v);try{const r=await fetch(u,{headers:headers(),cache:'no-store'});if(!r.ok)return[];const j=await r.json();return Array.isArray(j?.result)?j.result:[];}catch{return[];}}
async function routeNames(addresses){const out={};for(let i=0;i<addresses.length;i+=20){const batch=addresses.slice(i,i+20),u=new URL('https://api.routescan.io/v2/network/mainnet/evm/all/addresses');batch.forEach(a=>u.searchParams.append('ids',a));u.searchParams.set('limit','100');try{const r=await fetch(u,{headers:headers(),cache:'no-store'});if(!r.ok)continue;const j=await r.json();for(const x of(j?.items||[])){const a=String(x.address||'').toLowerCase(),n=normName(x.name||'');if(a&&n)out[a]={exchange:n[0],region:n[1],tag:x.name||'',source:'routescan-address-name'};}}catch{}}return out;}
async function nametag(address,chainId){try{const u=new URL(`https://api.routescan.io/v2/network/mainnet/evm/${chainId}/etherscan/api`);u.searchParams.set('module','nametag');u.searchParams.set('action','getaddresstag');u.searchParams.set('address',address);const r=await fetch(u,{headers:headers(),cache:'no-store'});if(!r.ok)return null;const j=await r.json(),x=j?.result||{};const text=[x.nametag,x.internal_nametag,x.shortdescription,...(Array.isArray(x.labels)?x.labels:[])].filter(Boolean).join(' | '),n=normName(text);return n?{exchange:n[0],region:n[1],tag:x.nametag||x.internal_nametag||text,source:'routescan-nametag'}:null;}catch{return null;}}
function collect(obj,out=[],depth=0){if(depth>10||obj==null)return out;if(typeof obj==='string'){if(obj.length<240)out.push(obj);return out}if(Array.isArray(obj)){for(const v of obj.slice(0,500))collect(v,out,depth+1);return out}if(typeof obj==='object')for(const v of Object.values(obj))collect(v,out,depth+1);return out;}
async function oklink(address,chainId){const key=process.env.OKLINK_API_KEY;if(!key)return null;try{const short=OKSHORT[chainId]||'POLYGON',u=`https://www.oklink.com/api/v5/tracker/entity-tag?chainShortName=${encodeURIComponent(short)}&address=${encodeURIComponent(address)}`,r=await fetch(u,{headers:{'Ok-Access-Key':key},cache:'no-store'});if(!r.ok)return null;const j=await r.json(),text=collect(j).join(' | '),n=normName(text);return n?{exchange:n[0],region:n[1],tag:(text.match(/(?:Binance|OKX|Coinbase|Bybit|Kraken|Gate(?:\.io)?|MEXC)[^|]{0,60}/i)||[])[0]||n[0],source:'oklink-tag'}:null;}catch{return null;}}
async function resolveLabels(all){const freq=new Map();for(const x of all)freq.set(x.counterparty,(freq.get(x.counterparty)||0)+1);const cps=[...freq.keys()].sort((a,b)=>freq.get(b)-freq.get(a)).slice(0,250),out=await routeNames(cps);for(const a of cps)if(KNOWN[a])out[a]={...KNOWN[a],source:'known-reservoir'};const unresolved=cps.filter(a=>!out[a]);for(let i=0;i<Math.min(unresolved.length,80);i+=8){const batch=unresolved.slice(i,i+8);await Promise.all(batch.map(async a=>{const chains=[...new Set(all.filter(x=>x.counterparty===a).map(x=>x.chainId))];for(const c of chains){let z=await nametag(a,c);if(!z)z=await oklink(a,c);if(z){out[a]=z;break;}}}));}return out;}
function tokenAmount(x){let amount=x.value;if(/^\d+$/.test(amount)&&x.tokenDecimals>=0){try{const d=BigInt(10)**BigInt(x.tokenDecimals),v=BigInt(amount);amount=`${v/d}${x.tokenDecimals?'.'+String(v%d).padStart(x.tokenDecimals,'0').replace(/0+$/,''):''}`.replace(/\.$/,'');}catch{}}return amount;}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const address=String(req.query?.address||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(address))return res.status(400).json({error:'Invalid address'});try{const pages=await Promise.all(CHAINS.map(async chainId=>{const [tok,tx]=await Promise.all([accountRows(address,chainId,'tokentx'),accountRows(address,chainId,'txlist')]);return{chainId,tok,tx};})),all=[];for(const p of pages){for(const x of p.tok){const from=String(x.from||'').toLowerCase(),to=String(x.to||'').toLowerCase(),cp=from===address?to:from;if(!/^0x[a-f0-9]{40}$/.test(cp)||cp===address)continue;all.push({kind:'ERC20',chainId:p.chainId,from,to,counterparty:cp,txHash:x.hash||'',timestamp:x.timeStamp?new Date(Number(x.timeStamp)*1000).toISOString():'',tokenSymbol:x.tokenSymbol||'',tokenName:x.tokenName||'',tokenDecimals:Number(x.tokenDecimal||0),value:String(x.value||'0'),method:x.functionName||''});}
for(const x of p.tx){const from=String(x.from||'').toLowerCase(),to=String(x.to||'').toLowerCase();if(from!==address&&to!==address)continue;const cp=from===address?to:from;if(!/^0x[a-f0-9]{40}$/.test(cp)||cp===address)continue;all.push({kind:'TX',chainId:p.chainId,from,to,counterparty:cp,txHash:x.hash||'',timestamp:x.timeStamp?new Date(Number(x.timeStamp)*1000).toISOString():'',tokenSymbol:'NATIVE',tokenName:'Native',tokenDecimals:18,value:String(x.value||'0'),method:x.functionName||x.methodId||''});}}
const uniq=new Map();for(const x of all){const k=[x.kind,x.chainId,x.txHash,x.counterparty].join('|');if(!uniq.has(k))uniq.set(k,x);}const rows=[...uniq.values()],labels=await resolveLabels(rows),hits=[];for(const x of rows){const lab=labels[x.counterparty];if(!lab)continue;hits.push({...x,direction:x.from===address?'實際帳戶 → 交易所':'交易所 → 實際帳戶',amount:tokenAmount(x),exchange:lab.exchange,region:lab.region,exchangeTag:lab.tag||'',source:lab.source||'label'});}return res.status(200).json({address,scannedChains:CHAINS,transfersScanned:rows.filter(x=>x.kind==='ERC20').length,directTxScanned:rows.filter(x=>x.kind==='TX').length,uniqueCounterparties:new Set(rows.map(x=>x.counterparty)).size,labelledCounterparties:Object.keys(labels).length,hits:hits.slice(0,300),diagnostic:{sampleCounterparties:[...new Set(rows.map(x=>x.counterparty))].slice(0,20)},source:'Routescan ERC-20 + direct tx history + address names + nametags + OKLink tags + known exchange labels'});}catch(e){return res.status(502).json({error:'History scan failed',detail:e?.message||String(e)});}}
