const CHAIN={1:'ETH',10:'OP',56:'BSC',137:'POLYGON',8453:'BASE',42161:'ARBITRUM',43114:'AVAXC'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const low=s=>String(s||'').trim().toLowerCase();
const addr=s=>/^0x[a-f0-9]{40}$/.test(low(s));
async function getJSON(url,key){const r=await fetch(url,{headers:{'Ok-Access-Key':key},cache:'no-store'});let j={};try{j=await r.json()}catch{}return{status:r.status,ok:r.ok,json:j}}
async function label(address,chainId,key){const u=`${process.env.PUBLIC_BASE_URL||'https://yuan-polymarket.vercel.app'}/api/oklink-label?address=${encodeURIComponent(address)}&chainId=${chainId}&_=${Date.now()}`;try{const r=await fetch(u,{cache:'no-store'});const j=await r.json();return j?.found?j:null}catch{return null}}
function clean(s){return String(s??'').replace(/\s+/g,' ').trim()}
function explicitTxTag(x){
  const hits=[]; const seen=new Set();
  function walk(v,k='',depth=0){if(depth>8||v==null)return;if(typeof v==='string'){const s=clean(v);if(!s||s.length>240)return;if(/tag|label|nametag|entitytag|addresstag|internal_nametag/i.test(k)){if(!seen.has(s)){seen.add(s);hits.push(s)}}return}if(Array.isArray(v)){for(const z of v.slice(0,100))walk(z,k,depth+1);return}if(typeof v==='object'){for(const [kk,vv] of Object.entries(v))walk(vv,kk,depth+1)}}
  walk(x);
  const exchange=/^(?:BitoPro|Binance|Coinbase|OKX|Bybit|Kraken|Gate\.io|MEXC|KuCoin|Bitget|MaiCoin|MaiCoin MAX|Upbit|Bithumb|HTX|Gemini|Bitfinex|Bitstamp)(?:[.:_\-]|\s|$)/i;
  const tag=hits.find(s=>exchange.test(s));
  return tag?{label:tag,evidence:'OKLink transaction explicit tag/label'}:null;
}
async function txs(address,chainId,key){const chain=CHAIN[chainId]||'POLYGON',out=[];for(const protocolType of ['transaction','internal','token_20']){for(let page=1;page<=5;page++){const u=new URL('https://www.oklink.com/api/v5/explorer/address/transaction-list');u.searchParams.set('chainShortName',chain);u.searchParams.set('address',address);u.searchParams.set('protocolType',protocolType);u.searchParams.set('limit','50');u.searchParams.set('page',String(page));const q=await getJSON(u,key);if(!q.ok||q.json?.code!=='0')break;const d=q.json?.data?.[0]||{},list=d.transactionLists||d.transactionList||[];out.push(...list.map(x=>({...x,protocolType,chainId})));const total=Number(d.totalPage||1);if(page>=total||!list.length)break;await sleep(120)}}return out}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const address=low(req.query?.address),chainId=Number(req.query?.chainId||137);if(!addr(address))return res.status(400).json({error:'Invalid address'});const key=process.env.OKLINK_API_KEY;if(!key)return res.status(200).json({ok:false,address,chainId,source:'OKLink',reason:'OKLINK_API_KEY not configured'});try{const direct=await label(address,chainId,key);if(direct)return res.status(200).json({ok:true,address,chainId,direct,firstLayer:[],source:'OKLink Tag'});const list=await txs(address,chainId,key),seen=new Set(),counterparties=[];
for(const x of list){const from=low(x.from||x.fromAddress),to=low(x.to||x.toAddress),cp=from===address?to:(to===address?from:'');if(!addr(cp)||cp===address||seen.has(cp))continue;seen.add(cp);const txTag=explicitTxTag(x);counterparties.push({address:cp,txId:x.txId||x.txid||'',from,to,amount:x.amount||'',symbol:x.symbol||x.transactionSymbol||'',transactionTime:x.transactionTime||'',protocolType:x.protocolType,chainId,txTag})}
const matches=[];for(const cp of counterparties){if(cp.txTag){matches.push({...cp,tag:{found:true,exchange:cp.txTag.label.split(/[.:_\-]/)[0].trim(),label:cp.txTag.label,tags:[cp.txTag.label],entityType:'exchange',evidence:cp.txTag.evidence},matchLevel:'FIRST_LAYER_MATCH'});continue}const tag=await label(cp.address,chainId,key);if(tag)matches.push({...cp,tag,matchLevel:'FIRST_LAYER_MATCH'});await sleep(180)}
return res.status(200).json({ok:true,address,chainId,direct:null,firstLayer:matches,firstLayerScanned:counterparties.length,transactionsScanned:list.length,source:'OKLink transactions → OKLink Tag'});}catch(e){return res.status(200).json({ok:false,address,chainId,source:'OKLink',error:String(e?.message||e)});}}