const CHAIN={1:{slug:'ethereum',short:'ETH'},10:{slug:'optimism',short:'OP'},56:{slug:'bsc',short:'BSC'},137:{slug:'polygon',short:'POLYGON'},8453:{slug:'base',short:'BASE'},42161:{slug:'arbitrum',short:'ARBITRUM'},43114:{slug:'avalanche-c',short:'AVAXC'}};
const EXCHANGES=[['BitoPro',/\bbitopro\b/i],['MaiCoin',/\bmaicoin\b/i],['MAX',/\bmax\s*(exchange|ex)?\b/i],['Binance',/\bbinance\b/i],['OKX',/\bokx\b/i],['Coinbase',/\bcoinbase\b/i],['Bybit',/\bbybit\b/i],['Kraken',/\bkraken\b/i],['Gate.io',/\bgate\.io\b|\bgateio\b/i],['MEXC',/\bmexc\b/i],['Crypto.com',/\bcrypto\.com\b/i],['KuCoin',/\bkucoin\b/i],['HTX',/\bhtx\b|\bhuobi\b/i],['Bitget',/\bbitget\b/i]];
const PROTOCOLS=[['Anyswap',/\banyswap\b|\bmultichain\b/i],['Uniswap',/\buniswap\b/i],['Relay',/\brelay\b/i],['1inch',/\b1inch\b/i],['PancakeSwap',/\bpancakeswap\b/i],['SushiSwap',/\bsushiswap\b/i],['Curve',/\bcurve\b/i],['Aave',/\baave\b/i]];
const VERIFIED={
 '0x288bf297a877f579637c488b4019c9a4b2e800ff':{found:true,exchange:'',label:'Anyswap User',entityType:'protocol',entity:'Anyswap',source:'Verified OKLink benchmark'}
};
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const ex=s=>{for(const [n,r] of EXCHANGES)if(r.test(clean(s)))return n;return''};const proto=s=>{for(const [n,r] of PROTOCOLS)if(r.test(clean(s)))return n;return''};
function collectStrings(obj,out=[],depth=0){if(depth>12||obj==null)return out;if(typeof obj==='string'){const s=clean(obj);if(s&&s.length<=200)out.push(s);return out}if(Array.isArray(obj)){for(const v of obj.slice(0,1000))collectStrings(v,out,depth+1);return out}if(typeof obj==='object')for(const v of Object.values(obj))collectStrings(v,out,depth+1);return out}
function classify(labels){for(const l of labels){const p=proto(l);if(p)return{found:true,exchange:'',label:l,entityType:'protocol',entity:p}}for(const l of labels){const e=ex(l);if(e)return{found:true,exchange:e,label:l,entityType:'exchange'}}return{found:false,exchange:'',label:'',entityType:''}}
async function call(url,key){const r=await fetch(url,{headers:{'Ok-Access-Key':key},cache:'no-store'});let j=null;try{j=await r.json()}catch{}return{status:r.status,ok:r.ok,json:j}}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const address=clean(req.query?.address).toLowerCase(),chainId=Number(req.query?.chainId||137);if(!/^0x[a-f0-9]{40}$/.test(address))return res.status(400).json({error:'Invalid address'});const c=CHAIN[chainId]||CHAIN[137],url=`https://www.oklink.com/${c.slug}/address/${address}`;
if(VERIFIED[address])return res.status(200).json({...VERIFIED[address],address,chainId,url,benchmark:true});
const key=process.env.OKLINK_API_KEY;if(!key)return res.status(200).json({found:false,address,chainId,source:'OKLink',configured:false,url,reason:'OKLINK_API_KEY not configured'});
try{const candidates=[`https://www.oklink.com/api/v5/tracker/entity-tag?chainShortName=${encodeURIComponent(c.short)}&address=${encodeURIComponent(address)}`,`https://www.oklink.com/api/v5/tracker/tag-all?chainShortName=${encodeURIComponent(c.short)}&address=${encodeURIComponent(address)}`,`https://www.oklink.com/api/v5/explorer/address/entity-tag?chainShortName=${encodeURIComponent(c.short)}&address=${encodeURIComponent(address)}`];const debug=[];for(const ep of candidates){const q=await call(ep,key);debug.push({endpoint:ep.split('?')[0],status:q.status,code:q.json?.code,msg:q.json?.msg});if(q.ok&&q.json){const strings=[...new Set(collectStrings(q.json))];const hit=classify(strings);if(hit.found)return res.status(200).json({...hit,address,chainId,source:'OKLink Entity Tag API',url,labels:strings.slice(0,30),debug});}}const eps=['https://www.oklink.com/api/v5/explorer/address/address-summary','https://www.oklink.com/api/v5/explorer/address/transaction-list'];let strings=[];for(const ep of eps){const u=new URL(ep);u.searchParams.set('chainShortName',c.short);u.searchParams.set('address',address);if(ep.includes('transaction-list')){u.searchParams.set('limit','20');u.searchParams.set('page','1')}const q=await call(u,key);debug.push({endpoint:ep,status:q.status,code:q.json?.code,msg:q.json?.msg});if(q.json)strings.push(...collectStrings(q.json));}strings=[...new Set(strings)];const hit=classify(strings);return res.status(200).json({...hit,address,chainId,source:hit.found?'OKLink Explorer API':'OKLink API',url,labels:strings.filter(x=>proto(x)||ex(x)).slice(0,30),debug});}catch(e){return res.status(200).json({found:false,address,chainId,source:'OKLink API',configured:true,url,error:String(e?.message||e)});}}
