const RPC={1:'https://cloudflare-eth.com',10:'https://mainnet.optimism.io',56:'https://bsc-dataseed.binance.org',137:'https://polygon-rpc.com',8453:'https://mainnet.base.org',42161:'https://arb1.arbitrum.io/rpc',43114:'https://api.avax.network/ext/bc/C/rpc'};
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const isAddr=x=>/^0x[a-f0-9]{40}$/i.test(String(x||''));
const addr=t=>/^0x[0-9a-fA-F]{64}$/.test(String(t||''))?'0x'+String(t).slice(-40).toLowerCase():'';
function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store');}
async function rpc(chainId,method,params){const u=RPC[Number(chainId)];if(!u)return null;try{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),cache:'no-store'});if(!r.ok)return null;const j=await r.json();return j?.result??null}catch{return null}}
async function resolvedTx(chainId,hash){if(!RPC[Number(chainId)]||!/^0x[a-fA-F0-9]{64}$/.test(String(hash||'')))return null;const [tx,receipt]=await Promise.all([rpc(chainId,'eth_getTransactionByHash',[hash]),rpc(chainId,'eth_getTransactionReceipt',[hash])]);if(!tx)return null;const transfers=[];for(const log of(receipt?.logs||[])){const topics=Array.isArray(log?.topics)?log.topics:[];if(String(topics[0]||'').toLowerCase()!==TRANSFER_TOPIC||topics.length<3)continue;const from=addr(topics[1]),to=addr(topics[2]);if(!from||!to)continue;transfers.push({token:String(log.address||'').toLowerCase(),from,to,value:String(log.data||'')});}return{hash:String(tx.hash||hash).toLowerCase(),chainId:Number(chainId),from:String(tx.from||'').toLowerCase(),to:String(tx.to||'').toLowerCase(),transfers};}
function rowsFrom(data){if(Array.isArray(data?.requests))return data.requests;if(Array.isArray(data?.data))return data.data;if(Array.isArray(data))return data;return[];}
function firstLayerFromTx(wallet,t){const out=[];const w=String(wallet||'').toLowerCase();let anchor='';if(t.from===w||t.to===w)anchor=w;else if(isAddr(t.to))anchor=t.to;else if(isAddr(t.from))anchor=t.from;
 for(const tr of(t.transfers||[])){let cp='',dir='';if(anchor&&tr.from===anchor&&tr.to!==anchor){cp=tr.to;dir='Relay -> Counterparty'}else if(anchor&&tr.to===anchor&&tr.from!==anchor){cp=tr.from;dir='Counterparty -> Relay'}else if(tr.from===w&&tr.to!==w){cp=tr.to;dir='Proxy -> Counterparty'}else if(tr.to===w&&tr.from!==w){cp=tr.from;dir='Counterparty -> Proxy'}
  if(cp&&isAddr(cp))out.push({chainId:t.chainId,txHash:t.hash,relayAddress:anchor,direction:dir,tokenContract:tr.token,rawAmount:tr.value,counterparty:cp});
 }
 if(!out.length&&(t.transfers||[]).length===1){const tr=t.transfers[0];let cp='';if(anchor===tr.from)cp=tr.to;else if(anchor===tr.to)cp=tr.from;else if(isAddr(tr.to))cp=tr.to;if(cp&&isAddr(cp))out.push({chainId:t.chainId,txHash:t.hash,relayAddress:anchor,direction:'Single ERC20 transfer',tokenContract:tr.token,rawAmount:tr.value,counterparty:cp});}
 return out;
}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!process.env.RELAY_API_KEY)return res.status(500).json({error:'RELAY_API_KEY is not configured'});const headers={Accept:'application/json','x-api-key':process.env.RELAY_API_KEY};
try{
 const requestId=String(req.query?.requestId||'').trim();
 if(requestId){const wallet=String(req.query?.wallet||'').trim().toLowerCase();const sr=await fetch(`https://api.relay.link/intents/status/v3?requestId=${encodeURIComponent(requestId)}`,{headers,cache:'no-store'});const text=await sr.text();if(!sr.ok)return res.status(sr.status).json({error:`Relay status HTTP ${sr.status}`,detail:text.slice(0,600)});let s={};try{s=JSON.parse(text)}catch{return res.status(502).json({error:'Relay status returned non-JSON'});}const originChainId=Number(s.originChainId||0),txs=[];for(const h of(s.inTxHashes||[])){const t=await resolvedTx(originChainId,h);if(t)txs.push(t);}const transfers=[];for(const t of txs)transfers.push(...firstLayerFromTx(wallet,t));return res.status(200).json({requestId,status:s.status||'',originChainId,destinationChainId:Number(s.destinationChainId||0),updatedAt:s.updatedAt||'',inTxHashes:s.inTxHashes||[],outTxHashes:s.txHashes||[],txs,transfers});}
 const wallet=String(req.query?.wallet||'').trim().toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(wallet))return res.status(400).json({error:'Invalid wallet'});
 const all=[],seen=new Set();let continuation='',pages=0;do{const q=new URLSearchParams({user:wallet,limit:'50',sortBy:'updatedAt',sortDirection:'desc'});if(continuation)q.set('continuation',continuation);const r=await fetch(`https://api.relay.link/requests/v2?${q}`,{headers,cache:'no-store'});const text=await r.text();if(!r.ok)return res.status(r.status).json({error:`Relay HTTP ${r.status}`,detail:text.slice(0,600)});let d={};try{d=JSON.parse(text)}catch{return res.status(502).json({error:'Relay returned non-JSON'});}for(const row of rowsFrom(d)){const id=String(row?.id||row?.requestId||row?.data?.id||'');if(id&&!seen.has(id)){seen.add(id);all.push({id,status:row?.status||'',createdAt:row?.createdAt||'',updatedAt:row?.updatedAt||''});}}continuation=String(d?.continuation||'');pages++;if(pages>=20)break;}while(continuation);
 return res.status(200).json({wallet,requests:all,count:all.length,pages,truncated:Boolean(continuation)});
}catch(e){return res.status(502).json({error:'First-layer Relay unavailable',detail:String(e?.message||e)});}}
