const isAddr=x=>/^0x[a-f0-9]{40}$/i.test(String(x||''));
function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store');}
function rowsFrom(data){if(Array.isArray(data?.requests))return data.requests;if(Array.isArray(data?.data))return data.data;if(Array.isArray(data))return data;return[];}
const low=x=>String(x||'').trim().toLowerCase();
function deepAddr(obj,names){const wanted=new Set(names.map(low)),seen=new Set();function walk(x,depth=0){if(!x||typeof x!=='object'||depth>8||seen.has(x))return'';seen.add(x);for(const [k,v] of Object.entries(x)){if(wanted.has(low(k))&&isAddr(v))return low(v)}for(const v of Object.values(x)){if(v&&typeof v==='object'){const z=walk(v,depth+1);if(z)return z}}return''}return walk(obj)}
function deepVal(obj,names){const wanted=new Set(names.map(low)),seen=new Set();function walk(x,depth=0){if(!x||typeof x!=='object'||depth>8||seen.has(x))return'';seen.add(x);for(const [k,v] of Object.entries(x)){if(wanted.has(low(k))&&v!==undefined&&v!==null&&typeof v!=='object'&&String(v)!=='')return v}for(const v of Object.values(x)){if(v&&typeof v==='object'){const z=walk(v,depth+1);if(z!==''&&z!==undefined)return z}}return''}return walk(obj)}
function summary(s){const originChainId=Number(s?.originChainId||deepVal(s,['originChainId','originChain','chainId'])||0),destinationChainId=Number(s?.destinationChainId||deepVal(s,['destinationChainId','destinationChain'])||0);return{requestId:String(s?.id||s?.requestId||deepVal(s,['requestId'])||''),status:String(s?.status||deepVal(s,['status'])||''),sender:deepAddr(s,['sender','user','from','originAddress']),recipient:deepAddr(s,['recipient','receiver','destinationAddress','recipientAddress']),originChainId,destinationChainId,inTxHashes:Array.isArray(s?.inTxHashes)?s.inTxHashes:[],outTxHashes:Array.isArray(s?.txHashes)?s.txHashes:(Array.isArray(s?.outTxHashes)?s.outTxHashes:[]),inputToken:deepVal(s,['inputToken','currencyIn','tokenIn']),inputAmount:deepVal(s,['inputAmount','amountIn']),outputToken:deepVal(s,['outputToken','currencyOut','tokenOut']),outputAmount:deepVal(s,['outputAmount','amountOut']),updatedAt:s?.updatedAt||deepVal(s,['updatedAt'])||''};}
function merge(a,b){return{requestId:b.requestId||a.requestId,status:b.status||a.status,sender:a.sender||b.sender,recipient:a.recipient||b.recipient,originChainId:a.originChainId||b.originChainId,destinationChainId:a.destinationChainId||b.destinationChainId,inTxHashes:b.inTxHashes?.length?b.inTxHashes:a.inTxHashes,outTxHashes:b.outTxHashes?.length?b.outTxHashes:a.outTxHashes,inputToken:a.inputToken||b.inputToken,inputAmount:a.inputAmount||b.inputAmount,outputToken:a.outputToken||b.outputToken,outputAmount:a.outputAmount||b.outputAmount,updatedAt:b.updatedAt||a.updatedAt};}
async function getRows(wallet,headers){const all=[],seen=new Set();let continuation='',pages=0;do{const q=new URLSearchParams({user:wallet,limit:'50',sortBy:'updatedAt',sortDirection:'desc'});if(continuation)q.set('continuation',continuation);const r=await fetch(`https://api.relay.link/requests/v2?${q}`,{headers,cache:'no-store'}),text=await r.text();if(!r.ok)throw Object.assign(Error(`Relay HTTP ${r.status}`),{status:r.status,detail:text.slice(0,600)});let d={};try{d=JSON.parse(text)}catch{throw Error('Relay returned non-JSON')}for(const row of rowsFrom(d)){const id=String(row?.id||row?.requestId||row?.data?.id||'');if(id&&!seen.has(id)){seen.add(id);all.push({...summary(row),id,raw:row})}}continuation=String(d?.continuation||'');pages++;if(pages>=20)break;}while(continuation);return{all,pages,truncated:Boolean(continuation)}}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!process.env.RELAY_API_KEY)return res.status(500).json({error:'RELAY_API_KEY is not configured'});const headers={Accept:'application/json','x-api-key':process.env.RELAY_API_KEY};try{const wallet=low(req.query?.wallet),requestId=String(req.query?.requestId||'').trim();if(!/^0x[a-f0-9]{40}$/.test(wallet))return res.status(400).json({error:'Invalid wallet'});
if(requestId){const list=await getRows(wallet,headers),row=list.all.find(x=>low(x.id)===low(requestId))||{};const sr=await fetch(`https://api.relay.link/intents/status/v3?requestId=${encodeURIComponent(requestId)}`,{headers,cache:'no-store'}),text=await sr.text();if(!sr.ok)return res.status(sr.status).json({error:`Relay status HTTP ${sr.status}`,detail:text.slice(0,600)});let s={};try{s=JSON.parse(text)}catch{return res.status(502).json({error:'Relay status returned non-JSON'})}const out=merge(row,summary(s));out.sources={requestRow:Boolean(row.id),status:true};return res.status(200).json(out)}
const list=await getRows(wallet,headers);return res.status(200).json({wallet,requests:list.all.map(({raw,...x})=>x),count:list.all.length,pages:list.pages,truncated:list.truncated});}catch(e){return res.status(e?.status||502).json({error:'Relay request unavailable',detail:e?.detail||String(e?.message||e)});}}
