const RPC={1:'https://cloudflare-eth.com',10:'https://mainnet.optimism.io',56:'https://bsc-dataseed.binance.org',137:'https://polygon-rpc.com',8453:'https://mainnet.base.org',42161:'https://arb1.arbitrum.io/rpc',43114:'https://api.avax.network/ext/bc/C/rpc'};
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const addr=t=>/^0x[0-9a-fA-F]{64}$/.test(String(t||''))?'0x'+String(t).slice(-40).toLowerCase():'';
async function rpc(chainId,method,params){const u=RPC[Number(chainId)];if(!u)return null;const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),cache:'no-store'});if(!r.ok)return null;const j=await r.json();return j?.result??null;}
async function resolvedTx(chainId,hash){if(!RPC[Number(chainId)]||!/^0x[a-fA-F0-9]{64}$/.test(String(hash||'')))return null;const [tx,receipt]=await Promise.all([rpc(chainId,'eth_getTransactionByHash',[hash]),rpc(chainId,'eth_getTransactionReceipt',[hash])]);if(!tx)return null;const transfers=[];for(const log of(receipt?.logs||[])){const topics=Array.isArray(log?.topics)?log.topics:[];if(String(topics[0]||'').toLowerCase()!==TRANSFER_TOPIC||topics.length<3)continue;const from=addr(topics[1]),to=addr(topics[2]);if(!from||!to)continue;transfers.push({token:String(log.address||'').toLowerCase(),from,to,value:String(log.data||'')});}return{hash:String(tx.hash||hash).toLowerCase(),chainId:Number(chainId),from:String(tx.from||'').toLowerCase(),to:String(tx.to||'').toLowerCase(),transfers};}
function rowsFrom(data){if(Array.isArray(data?.requests))return data.requests;if(Array.isArray(data?.data))return data.data;if(Array.isArray(data))return data;return[];}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const headers={Accept:'application/json'};if(process.env.RELAY_API_KEY)headers['x-api-key']=process.env.RELAY_API_KEY;
try{
 const requestId=String(req.query?.requestId||'').trim();
 if(requestId){const wallet=String(req.query?.wallet||'').trim().toLowerCase();const sr=await fetch(`https://api.relay.link/intents/status/v3?requestId=${encodeURIComponent(requestId)}`,{headers,cache:'no-store'});const text=await sr.text();if(!sr.ok)return res.status(sr.status).json({error:`Relay status HTTP ${sr.status}`,detail:text.slice(0,600)});let s={};try{s=JSON.parse(text)}catch{return res.status(502).json({error:'Relay status returned non-JSON'});}const originChainId=Number(s.originChainId||0),txs=[];for(const h of(s.inTxHashes||[])){const t=await resolvedTx(originChainId,h);if(t)txs.push(t);}const transfers=[];for(const t of txs){for(const tr of(t.transfers||[])){const a=tr.from===wallet,b=tr.to===wallet;if(wallet&&a!==b){transfers.push({chainId:t.chainId,txHash:t.hash,direction:a?'Proxy -> Counterparty':'Counterparty -> Proxy',tokenContract:tr.token,rawAmount:tr.value,counterparty:a?tr.to:tr.from});}}}res.setHeader('Cache-Control','no-store');return res.status(200).json({requestId,status:s.status||'',originChainId,destinationChainId:Number(s.destinationChainId||0),updatedAt:s.updatedAt||'',inTxHashes:s.inTxHashes||[],outTxHashes:s.txHashes||[],transfers});}
 const wallet=String(req.query?.wallet||'').trim().toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(wallet))return res.status(400).json({error:'Invalid wallet'});
 const all=[],seen=new Set();let continuation='',pages=0;do{const q=new URLSearchParams({user:wallet,limit:'50',sortDirection:'desc'});if(continuation)q.set('continuation',continuation);const r=await fetch(`https://api.relay.link/requests/v2?${q}`,{headers,cache:'no-store'});const text=await r.text();if(!r.ok)return res.status(r.status).json({error:`Relay HTTP ${r.status}`,detail:text.slice(0,600)});let d={};try{d=JSON.parse(text)}catch{return res.status(502).json({error:'Relay returned non-JSON'});}for(const row of rowsFrom(d)){const id=String(row?.id||row?.requestId||row?.data?.id||'');if(id&&!seen.has(id)){seen.add(id);all.push({id,status:row?.status||'',createdAt:row?.createdAt||'',updatedAt:row?.updatedAt||''});}}continuation=String(d?.continuation||'');pages++;if(pages>=20)break;}while(continuation);
 res.setHeader('Cache-Control','no-store');return res.status(200).json({wallet,requests:all,count:all.length,pages,truncated:Boolean(continuation)});
}catch(e){return res.status(502).json({error:'First-layer Relay unavailable',detail:String(e?.message||e)});}}
